import time
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://accounts.teachmint.com/")
time.sleep(10)
driver.find_element(By.XPATH, "//input[@id='user-input']").send_keys("0000020232")
time.sleep(10)
driver.find_element(By.XPATH, "//input[@type='submit']").click()

driver.find_element(By.XPATH, "//div[@class='otp-container']/input[1]").send_keys("1")
driver.find_element(By.XPATH, "//div[@class='otp-container']/input[2]").send_keys("2")
driver.find_element(By.XPATH, "//div[@class='otp-container']/input[3]").send_keys("0")
driver.find_element(By.XPATH, "//div[@class='otp-container']/input[4]").send_keys("9")
driver.find_element(By.XPATH, "//div[@class='otp-container']/input[5]").send_keys("9")
driver.find_element(By.XPATH, "//div[@class='otp-container']/input[6]").send_keys("2")
time.sleep(5)
driver.find_element(By.XPATH, "//button[@onclick='verifyOtp()']").click()
time.sleep(10)
driver.find_element(By.XPATH,"(//div[@class='profile-data-cont'])[2]").click()
time.sleep(10)
driver.find_element(By.XPATH,"//span[@data-qa='icon-administrator']").click()
driver.find_element(By.XPATH,"(//a[@class='Sidebar_sidebarLink__39rXm'])[1]").click()
time.sleep(5)
driver.find_element(By.XPATH,"(//span[text()='View All'])[1]")
time.sleep(5)
driver.find_element(By.XPATH,"//h6[text()='School leaving certificate']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[text()='Generate']").click()
time.sleep(5)
driver.find_element(By.XPATH,"(//input[@type='checkbox'])[2]").click()
driver.find_element(By.XPATH,"//div[text()='Generate']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//input[@placeholder='Remarks']").send_keys("Leaving Certificate Updated")
time.sleep(5)
#driver.find_element(By.XPATH,"(//button[@data-qa='button,disabled-false'])[1]").click()
driver.find_element(By.XPATH,"(//button[@data-qa='button,disabled-false'])[2]").click()
time.sleep(5)
driver.find_element(By.ID,"download").click()
time.sleep(10)
windows_list = driver.window_handles
driver.switch_to.window(windows_list[0])
time.sleep(5)
driver.find_element(By.XPATH,"//a[text()='Certificates and Documents']").click()
time.sleep(5)
driver.find_element(By.XPATH,"(//span[text()='View All'])[2]").click()
time.sleep(5)
driver.find_element(By.XPATH,"(//p[text()='Action']//following::span[@data-qa='icon-ellipsisVertical'])[1]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[text()='Preview']").click()
time.sleep(30)
driver.close()