from selenium.webdriver.common.by import By
choose_option_ticket_locator =(By.XPATH,"//input[@type='radio' and @value='radio_678']")
textBox_firstName_locator = (By.XPATH, "//input[@id = 'firstname' and @name ='firstname'][1]")
textBox_lastName_locator = (By.XPATH, "//input[@id = 'firstname' and @name ='firstname'][2]")
textBox_dateOfBirth_locator = (By.XPATH, "//input[@id = 'birthday']")
radioButton_Male_locator = (By.XPATH, "//input[@id = 'male']")
select_Passanger_locator = (By.ID,'admorepass')
radioButton_TravelDetails_locator = (By.XPATH,"//input[@id='roundtrip']")
textBox_FromCity_locator = (By.XPATH, "//input[@id='fromcity']")
textBox_DestinationCity_locator = (By.XPATH, "//input[@id='destcity']")
textBox_DepartureDate_locator = (By.XPATH, "//input[@id='departdate']")
textBox_ReturnDate_locator = (By.XPATH, "//input[@id='returndate']")
textBox_VisaInterviewDate_locator = (By.XPATH, "//input[@id='visadate']")
radioButton_receiveDummyTicket_locator = (By.XPATH, "//input[@id='eamil']")
billing_name_field_locator = (By.ID, "billing_name")
billing_phone_field_locator = (By.ID, "billing_phone")
billing_email_field_locator = (By.ID, "billing_email")
billing_address_field_locator = (By.XPATH, "//input[@id='billing_address']")
country_dropdown_locator = (By.ID, "billing_country")
textBox_zip_locator = (By.XPATH, "//input[@id='postcode']")
textBox_streetAddress1_locator = (By.XPATH, "//input[@id='street_address1']")
textBox_streetAddress2_locator = (By.XPATH, "//input[@id='street_address2']")
checkBox_MostVisitedCities_locator =(By.XPATH,"//tr[8]//parent::td//child::input[@type='checkbox']")

